site_name: DORIS Inicio

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: none
    navigation_depth: 4
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search

markdown_extensions:
  - footnotes
  - attr_list

nav:
    - DORIS:
        - Información general: 'index.md'
        - Solución integral de la CIE-11: 'icd11mde2e.md'
        - Resumen: 'overview.md'
    - Versión en línea: 
        - Doris en línea: 'doris-web.md'
    - Versión de escritorio: 
        - Notas de la versión: 'doris-desktop-release-notes.md'
        - Descarga e instalación: 'doris-desktop-download-installation.md'
        - Guía para el usuario: 'doris-desktop-user-guide.md'
        - Formatos de archivos: 'supported-file-formats.md'
    - Uso de DORIS desde otro software: 
        - Uso de DORIS desde la API de la CIE: 'doris-api.md'

